title: sophie chou
description: Clinton, TN | schou2@nd.edu
theme: jekyll-theme-cayman

nav:
  - title: Experience
    url: /experience/
  - title: Courses
    url: /courses/
  - title: Activities
    url: /activities/
  - title: Skills
    url: /skills/
