# title: sophie chou
# description: Clinton, TN | schou2@nd.edu
# theme: jekyll-theme-cayman

# nav:
#   - title: Experience
#     url: /experience.md/
#   - title: Courses & Projects
#     url: /courses.md/
#   - title: Activities & Societies
#     url: /activities.md/
#   - title: Skills
#     url: /skills.md/
